import RNHTMLtoPDF from 'react-native-html-to-pdf';

export async function generatePDFReport({
  pH,
  temperature,
  turbidity,
  salinity,
  chartBase64,
  aiInsights,
  aiSuggestions,
  statusSummary,
  dateRange,
}) {
  const statusColor =
    statusSummary === 'Good'
      ? 'green'
      : statusSummary === 'Caution'
      ? 'orange'
      : 'red';

  const html = `
    <html>
      <head>
        <style>
          body { font-family: Arial, sans-serif; padding: 20px; }
          h1 { color: #007bff; }
          h2 { color: #444; margin-top: 30px; }
          .status { font-weight: bold; color: ${statusColor}; }
          .section { margin-bottom: 25px; }
          .label { font-weight: bold; margin-bottom: 4px; display: block; }
          .card { border: 1px solid #ccc; padding: 10px; border-radius: 6px; background: #f9f9f9; }
          img { width: 100%; max-width: 500px; margin-top: 10px; border-radius: 4px; }
        </style>
      </head>
      <body>
        <h1>PureFlow Water Quality Report</h1>
        <div class="section">
          <span class="label">Report Range:</span>
          <div>${dateRange.from} – ${dateRange.to}</div>
        </div>

        <div class="section">
          <h2>Sensor Data Summary</h2>
          <div class="card">
            <p><strong>pH Level:</strong> ${pH}</p>
            <p><strong>Temperature:</strong> ${temperature} °C</p>
            <p><strong>Turbidity:</strong> ${turbidity} NTU</p>
            <p><strong>Salinity:</strong> ${salinity} ppt</p>
          </div>
        </div>

        <div class="section">
          <h2>Overall Water Quality Status</h2>
          <p class="status">${statusSummary}</p>
        </div>

        <div class="section">
          <h2>Data Visualization</h2>
          <img src="data:image/png;base64,${chartBase64}" />
        </div>

        <div class="section">
          <h2>AI Insights</h2>
          <div class="card">${aiInsights}</div>
        </div>

        <div class="section">
          <h2>AI Recommendations</h2>
          <div class="card">${aiSuggestions}</div>
        </div>

        <footer style="margin-top: 40px; font-size: 12px; text-align: center;">
          Generated by PureFlow &middot; ${new Date().toLocaleString()}
        </footer>
      </body>
    </html>
  `;

  const file = await RNHTMLtoPDF.convert({
    html,
    fileName: `pureflow_report_${Date.now()}`,
    directory: 'Documents',
  });

  return file.filePath;
}
